---

- name : install fail2ban packages
  become: True
  apt  :
    name  : "{{ fail2ban_packages }}"
    state : "{{ fail2ban_package_state }}"
    update_cache     : True
    cache_valid_time : 3600
  notify :
    - restart fail2ban
